name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Check import structure
      working-directory: backend
      run: |
        python -c "from shared.config import get_settings; print('✅ Config module imports correctly')"
        python -c "from ingestion.extractors import get_extractor; print('✅ Extractor module imports correctly')"
        python -c "from ingestion.storage.vector_store import VectorStore; print('✅ Vector store module imports correctly')"
        python -c "from interface.cli.ask import answer; print('✅ CLI module imports correctly')"
    
    - name: Run tests
      working-directory: backend
      run: |
        pytest tests/ -v --tb=short
    
    - name: Validate configuration template
      working-directory: backend
      run: |
        python -c "
        import yaml
        from pathlib import Path
        config = yaml.safe_load(Path('shared/config.yaml.template').read_text())
        required_keys = ['sync_root', 'db_path', 'vector_path', 'embed_model', 'openai_api_key']
        for key in required_keys:
            assert key in config, f'Missing required config key: {key}'
        print('✅ Configuration template is valid')
        "
    
    - name: Test setup script
      run: |
        python setup.py
        echo "✅ Post-clone setup script runs successfully"
